import { __makeTemplateObject } from "tslib";
import { css } from 'emotion';
import { stylesFactory } from '../../themes';
export var getModalStyles = stylesFactory(function (theme) {
    var backdropBackground = theme.colors.bg3;
    return {
        modal: css(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n      position: fixed;\n      z-index: ", ";\n      background: ", ";\n      box-shadow: 0 0 20px ", ";\n      background-clip: padding-box;\n      outline: none;\n      width: 750px;\n      max-width: 100%;\n      left: 0;\n      right: 0;\n      margin-left: auto;\n      margin-right: auto;\n      top: 10%;\n    "], ["\n      position: fixed;\n      z-index: ", ";\n      background: ", ";\n      box-shadow: 0 0 20px ", ";\n      background-clip: padding-box;\n      outline: none;\n      width: 750px;\n      max-width: 100%;\n      left: 0;\n      right: 0;\n      margin-left: auto;\n      margin-right: auto;\n      top: 10%;\n    "])), theme.zIndex.modal, theme.colors.bodyBg, theme.colors.dropdownShadow),
        modalBackdrop: css(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n      position: fixed;\n      top: 0;\n      right: 0;\n      bottom: 0;\n      left: 0;\n      z-index: ", ";\n      background-color: ", ";\n      opacity: 0.7;\n    "], ["\n      position: fixed;\n      top: 0;\n      right: 0;\n      bottom: 0;\n      left: 0;\n      z-index: ", ";\n      background-color: ", ";\n      opacity: 0.7;\n    "])), theme.zIndex.modalBackdrop, backdropBackground),
        modalHeader: css(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n      label: modalHeader;\n      background: ", ";\n      border-bottom: 1px solid ", ";\n      display: flex;\n      height: 42px;\n    "], ["\n      label: modalHeader;\n      background: ", ";\n      border-bottom: 1px solid ", ";\n      display: flex;\n      height: 42px;\n    "])), theme.colors.bg2, theme.colors.pageHeaderBorder),
        modalHeaderTitle: css(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n      font-size: ", ";\n      margin: 0 ", ";\n      display: flex;\n      align-items: center;\n      line-height: 42px;\n    "], ["\n      font-size: ", ";\n      margin: 0 ", ";\n      display: flex;\n      align-items: center;\n      line-height: 42px;\n    "])), theme.typography.size.lg, theme.spacing.md),
        modalHeaderIcon: css(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n      margin-right: ", ";\n      font-size: inherit;\n      &:before {\n        vertical-align: baseline;\n      }\n    "], ["\n      margin-right: ", ";\n      font-size: inherit;\n      &:before {\n        vertical-align: baseline;\n      }\n    "])), theme.spacing.md),
        modalHeaderClose: css(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n      height: 100%;\n      display: flex;\n      align-items: center;\n      flex-grow: 1;\n      justify-content: flex-end;\n      padding-right: ", ";\n    "], ["\n      height: 100%;\n      display: flex;\n      align-items: center;\n      flex-grow: 1;\n      justify-content: flex-end;\n      padding-right: ", ";\n    "])), theme.spacing.sm),
        modalContent: css(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n      padding: calc(", " * 2);\n      overflow: auto;\n      width: 100%;\n      max-height: calc(90vh - ", " * 2);\n    "], ["\n      padding: calc(", " * 2);\n      overflow: auto;\n      width: 100%;\n      max-height: calc(90vh - ", " * 2);\n    "])), theme.spacing.d, theme.spacing.d),
    };
});
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7;
//# sourceMappingURL=getModalStyles.js.map