import { __makeTemplateObject } from "tslib";
import { stylesFactory } from '../../themes/stylesFactory';
import { css } from 'emotion';
export var getSelectStyles = stylesFactory(function (theme) {
    var bgColor = theme.colors.formInputBg;
    var menuShadowColor = theme.colors.dropdownShadow;
    var optionBgHover = theme.colors.dropdownOptionHoverBg;
    var multiValueContainerBg = theme.colors.bg2;
    var multiValueColor = theme.colors.text;
    return {
        menu: css(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n      label: grafana-select-menu;\n      background: ", ";\n      box-shadow: 0px 4px 4px ", ";\n      position: relative;\n      min-width: 100%;\n      z-index: 1;\n    "], ["\n      label: grafana-select-menu;\n      background: ", ";\n      box-shadow: 0px 4px 4px ", ";\n      position: relative;\n      min-width: 100%;\n      z-index: 1;\n    "])), bgColor, menuShadowColor),
        option: css(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n      label: grafana-select-option;\n      padding: 8px;\n      display: flex;\n      align-items: center;\n      flex-direction: row;\n      flex-shrink: 0;\n      white-space: nowrap;\n      cursor: pointer;\n      border-left: 2px solid transparent;\n      &:hover {\n        background: ", ";\n      }\n    "], ["\n      label: grafana-select-option;\n      padding: 8px;\n      display: flex;\n      align-items: center;\n      flex-direction: row;\n      flex-shrink: 0;\n      white-space: nowrap;\n      cursor: pointer;\n      border-left: 2px solid transparent;\n      &:hover {\n        background: ", ";\n      }\n    "])), optionBgHover),
        optionImage: css(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n      label: grafana-select-option-image;\n      width: 16px;\n      margin-right: 10px;\n    "], ["\n      label: grafana-select-option-image;\n      width: 16px;\n      margin-right: 10px;\n    "]))),
        optionDescription: css(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n      label: grafana-select-option-description;\n      font-weight: normal;\n      font-size: ", ";\n      color: ", ";\n      white-space: normal;\n    "], ["\n      label: grafana-select-option-description;\n      font-weight: normal;\n      font-size: ", ";\n      color: ", ";\n      white-space: normal;\n    "])), theme.typography.size.sm, theme.colors.textWeak),
        optionBody: css(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n      label: grafana-select-option-body;\n      display: flex;\n      font-weight: ", ";\n      flex-direction: column;\n      flex-grow: 1;\n    "], ["\n      label: grafana-select-option-body;\n      display: flex;\n      font-weight: ", ";\n      flex-direction: column;\n      flex-grow: 1;\n    "])), theme.typography.weight.semibold),
        optionFocused: css(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n      label: grafana-select-option-focused;\n      background: ", ";\n      border-image: linear-gradient(#f05a28 30%, #fbca0a 99%);\n      border-image-slice: 1;\n      border-style: solid;\n      border-top: 0;\n      border-right: 0;\n      border-bottom: 0;\n      border-left-width: 2px;\n    "], ["\n      label: grafana-select-option-focused;\n      background: ", ";\n      border-image: linear-gradient(#f05a28 30%, #fbca0a 99%);\n      border-image-slice: 1;\n      border-style: solid;\n      border-top: 0;\n      border-right: 0;\n      border-bottom: 0;\n      border-left-width: 2px;\n    "])), optionBgHover),
        singleValue: css(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n      label: grafana-select-single-value;\n      color: ", ";\n      white-space: nowrap;\n      overflow: hidden;\n      text-overflow: ellipsis;\n      box-sizing: border-box;\n      max-width: 100%;\n    "], ["\n      label: grafana-select-single-value;\n      color: ", ";\n      white-space: nowrap;\n      overflow: hidden;\n      text-overflow: ellipsis;\n      box-sizing: border-box;\n      max-width: 100%;\n    "])), theme.colors.formInputText),
        valueContainer: css(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n      label: grafana-select-value-container;\n      align-items: center;\n      display: flex;\n      position: relative;\n      box-sizing: border-box;\n      flex: 1 1 0%;\n      outline: none;\n      overflow: hidden;\n    "], ["\n      label: grafana-select-value-container;\n      align-items: center;\n      display: flex;\n      position: relative;\n      box-sizing: border-box;\n      flex: 1 1 0%;\n      outline: none;\n      overflow: hidden;\n    "]))),
        valueContainerMulti: css(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n      label: grafana-select-value-container-multi;\n      flex-wrap: wrap;\n    "], ["\n      label: grafana-select-value-container-multi;\n      flex-wrap: wrap;\n    "]))),
        loadingMessage: css(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n      label: grafana-select-loading-message;\n      padding: ", ";\n      text-align: center;\n      width: 100%;\n    "], ["\n      label: grafana-select-loading-message;\n      padding: ", ";\n      text-align: center;\n      width: 100%;\n    "])), theme.spacing.sm),
        multiValueContainer: css(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n      label: grafana-select-multi-value-container;\n      display: flex;\n      align-items: center;\n      line-height: 1;\n      background: ", ";\n      border-radius: ", ";\n      margin: 0 ", " 0 0;\n      padding: ", " 0 ", " ", ";\n      color: ", ";\n      font-size: ", ";\n    "], ["\n      label: grafana-select-multi-value-container;\n      display: flex;\n      align-items: center;\n      line-height: 1;\n      background: ", ";\n      border-radius: ", ";\n      margin: 0 ", " 0 0;\n      padding: ", " 0 ", " ", ";\n      color: ", ";\n      font-size: ", ";\n    "])), multiValueContainerBg, theme.border.radius.sm, theme.spacing.sm, theme.spacing.xxs, theme.spacing.xxs, theme.spacing.sm, multiValueColor, theme.typography.size.sm),
        multiValueRemove: css(templateObject_12 || (templateObject_12 = __makeTemplateObject(["\n      label: grafana-select-multi-value-remove;\n      margin: 0 ", ";\n      cursor: pointer;\n    "], ["\n      label: grafana-select-multi-value-remove;\n      margin: 0 ", ";\n      cursor: pointer;\n    "])), theme.spacing.xs),
    };
});
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11, templateObject_12;
//# sourceMappingURL=getSelectStyles.js.map