name: Backend

# Suppress Spinner because it appears as warnings
env:
  SUPPRESS_SPINNER: true

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches:
      - 'master' 
    paths:
      - '*'
      - '.github/workflows/backend.yml'
      - 'common/**'
      - 'backend/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history
      
      # Get repo metadata so we can use it in the build scripts
      - name: Repo metadata
        id: repo
        uses: actions/github-script@v5
        with:
          script: |
            const repo = await github.rest.repos.get({owner: context.repo.owner, repo: context.repo.repo})
            return repo.data

      # Caching
      - name: Cache Gradle deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Setup Environments
      - name: Setup Java
        uses: actions/setup-java@v3.1.1
        with:
          distribution: 'temurin'
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '12'
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Build Server Projects
        run: ./gradlew clean && ./gradlew build
      
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Release Server Projects
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_USER_TOKEN: ${{ secrets.OSSRH_USER_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ./gradlew publish \
          -PversionPostfix=SNAPSHOT \
          -Psigning.gnupg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
          -Psigning.gnupg.keyName=$(gpg --list-secret-keys --keyid-format LONG | grep "sec" | awk -F'[/ ]' '{print $5}' | head -n 1)

      # Analyze
      - name: Analyze sprout-core
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CORE }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew :sprout-core:sonarqube --info

      - name: Analyze sprout-spring-boot-starter
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_STARTER }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew :sprout-spring-boot-starter:sonarqube --info

      - name: Analyze sprout-server
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SERVER }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew :sprout-server:sonarqube --info

      - name: Analyze sprout-modules-forms
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FORMS }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew :sprout-modules-forms:sonarqube --info
      
      # Setup for Docker build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      # Set some output variables based on the repo metadata
      - name: Prepare Server Docker Image
        id: prep_server_docker
        run: |
          DOCKER_IMAGE=savantly/sprout-server
          VERSION=noop
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
              VERSION=latest
            fi
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            MINOR=${VERSION%.*}
            MAJOR=${MINOR%.*}
            TAGS="$TAGS,${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"
          elif [ "${{ github.event_name }}" = "push" ]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      
      # Build and push server docker image
      - name: Build and push
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          context: ./backend/server
          file: ./backend/server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep_server_docker.outputs.tags }}
          labels: |
            org.opencontainers.image.title=${{ fromJson(steps.repo.outputs.result).name }}
            org.opencontainers.image.description=${{ fromJson(steps.repo.outputs.result).description }}
            org.opencontainers.image.url=${{ fromJson(steps.repo.outputs.result).html_url }}
            org.opencontainers.image.source=${{ fromJson(steps.repo.outputs.result).clone_url }}
            org.opencontainers.image.version=${{ steps.prep_server_docker.outputs.version }}
            org.opencontainers.image.created=${{ steps.prep_server_docker.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ fromJson(steps.repo.outputs.result).license.spdx_id }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ""
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
      - name: Deploy to Heroku
        run: ./scripts/deployHeroku.sh