name: Publish packages on release

# Suppress Spinner because it appears as warnings
env:
  SUPPRESS_SPINNER: true

on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'temurin'
          java-version: 11

      - uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'

      - name: Cache Gradle deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
  
      - name: Cache Rush temp files
        uses: actions/cache@v2
        with:
          path: |
            common/temp
          key: ${{ runner.os }}-node-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Rush Update
        run: node common/scripts/install-run-rush.js update
  
      - name: Rush build
        run: node common/scripts/install-run-rush.js build --verbose
        env:
          CI: false
      
      - name: NPM Publish
        run: node common/scripts/install-run-rush.js npm:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish java packages
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_USER_TOKEN: ${{ secrets.OSSRH_USER_TOKEN }}
        run: |
          ./gradlew publish \
          -PversionPostfix=SNAPSHOT \
          -Psigning.gnupg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
          -Psigning.gnupg.keyName=$(gpg --list-secret-keys --keyid-format LONG | grep "sec" | awk -F'[/ ]' '{print $5}' | head -n 1)

      - name: Build Storybook
        run: node common/scripts/install-run-rush.js storybook:deploy
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
